services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_yarn:/app/.yarn
    ports:
      - "${EXPOSE_APP_PORT}:3000"

volumes:
  frontend_node_modules:
  frontend_yarn:
